# Generated by Django 4.1.5 on 2023-02-08 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("content", models.CharField(max_length=200)),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 8, 13, 14, 29, 733714)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileSys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=64)),
                ("uploader", models.CharField(max_length=20)),
                ("file_size", models.IntegerField(max_length=4)),
                ("first_upload_time", models.DateTimeField()),
                ("last_upload_time", models.DateTimeField()),
            ],
        ),
    ]
