# Generated by Django 4.1.5 on 2023-02-08 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 8, 16, 4, 48, 511203)
            ),
        ),
    ]
