# Generated by Django 4.1.5 on 2023-02-14 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0003_alter_comment_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 14, 15, 36, 59, 605264)
            ),
        ),
    ]
