# Generated by Django 4.1.5 on 2023-03-15 07:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0006_publication_alter_comment_created_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 15, 15, 45, 50, 493400)
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 15, 15, 45, 50, 491400)
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reporter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="example.reporter",
            ),
            preserve_default=False,
        ),
    ]
